# Generated by Django 4.1 on 2022-08-16 21:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_superadmin_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationManager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('station_name', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('business_reg_num', models.IntegerField()),
            ],
            options={
                'db_table': '',
            },
            bases=('back.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='superadmin',
            options={},
        ),
        migrations.AlterModelTable(
            name='superadmin',
            table='',
        ),
    ]
