# Generated by Django 4.1 on 2022-08-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_stationmanager_alter_superadmin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stationmanager',
            table='StationManager',
        ),
        migrations.AlterModelTable(
            name='superadmin',
            table='SuperAdmin',
        ),
    ]
