# Generated by Django 4.1 on 2022-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_stationmanager_table_alter_superadmin_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmanager',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
