# Generated by Django 4.1 on 2022-08-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_stationmanager_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmanager',
            name='account_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
